# Generated by Django 3.2.4 on 2021-11-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_previously_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
