# Generated by Django 3.2.4 on 2021-11-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='choinBalance',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
