# Generated by Django 3.2.4 on 2021-11-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0003_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
