# Generated by Django 3.2.8 on 2021-10-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0004_alter_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
