# Generated by Django 3.2.8 on 2021-11-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0004_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemableitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
