# Generated by Django 3.2.4 on 2021-11-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
