# Generated by Django 3.2.8 on 2021-11-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0005_alter_redeemableitem_quantity'),
        ('leadership', '0006_delete_category'),
    ]

    operations = [
    ]
