# Generated by Django 3.2.8 on 2021-11-11 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0003_alter_wallet_choinbalance'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeem',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leadership.redeemableitem'),
        ),
    ]
