# Generated by Django 3.2.4 on 2021-11-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemed',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
