# Generated by Django 3.2.4 on 2021-11-05 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0004_wallet'),
        ('student', '0002_redeem_rewardeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('completed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadership.redeemableitem')),
            ],
        ),
        migrations.RemoveField(
            model_name='rewardeditem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='rewardeditem',
            name='reward',
        ),
        migrations.DeleteModel(
            name='Redeem',
        ),
        migrations.DeleteModel(
            name='RewardedItem',
        ),
    ]
