# Generated by Django 3.2.8 on 2021-11-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_redeem_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeem',
            name='reward',
        ),
    ]
