# Generated by Django 3.2.8 on 2021-11-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_redeemed'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemed',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
