# Generated by Django 3.2.8 on 2021-11-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_redeemed_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemed',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
