# Generated by Django 3.2.8 on 2021-11-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_redeemed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Redeemed',
        ),
    ]
