# Generated by Django 3.2.8 on 2021-11-08 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_redeem_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeem',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
