# Generated by Django 3.2.8 on 2021-11-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_redeemed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemed',
            name='product',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
