# Generated by Django 3.2.8 on 2021-11-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_redeem_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardeditem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
