# Generated by Django 3.2.8 on 2021-11-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_alter_transaction_time'),
        ('student', '0006_alter_redeemed_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemed',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leadership.redeemableitem'),
        ),
    ]
