# Generated by Django 3.2.8 on 2021-11-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0005_alter_redeemableitem_quantity'),
        ('student', '0006_alter_rewardeditem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardeditem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.redeem'),
        ),
        migrations.AlterField(
            model_name='rewardeditem',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leadership.redeemableitem'),
        ),
    ]
