# Generated by Django 3.2.8 on 2021-11-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20211105_0807'),
        ('student', '0011_alter_rewardeditem_quantity'),
    ]

    operations = [
    ]
